# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: "2"

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    # - depguard  # Many import violations
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    # - funlen  # Some test functions are long
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - godot  # Comment style
    # - goheader  # Header checks
    - mnd
    - goprintffuncname
    # - gosec  # Security warnings
    # - lll  # Many long lines
    - misspell
    - nakedret
    - nilnil
    # - noctx  # Context not always needed
    # - nolintlint  # Noisy
    # - prealloc  # Minor optimization
    - predeclared
    # - revive  # Style warnings
    # - stylecheck  # Style warnings
    # - tagliatelle  # Tag formatting
    # - testpackage  # Test package naming
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
    - errcheck
    - staticcheck
  settings:
    gofumpt:
      module-path: github.com/open-edge-platform/infra-external/loca-templates
    depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/open-edge-platform
          - github.com/deepmap/oapi-codegen
          - github.com/oapi-codegen/echo-middleware
          - github.com/getkin/kin-openapi
          - github.com/golang-jwt/jwt/v5
          - github.com/google/uuid
          - github.com/labstack/echo/v4
          - github.com/labstack/echo-contrib/echoprometheus
          - github.com/modern-go/reflect2
          - github.com/onosproject/onos-lib-go
          - github.com/stretchr/testify
          - github.com/viant/xunsafe
          - github.com/grpc-ecosystem/go-grpc-middleware
          - go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp
          - golang.org/x/net
          - google.golang.org/grpc
          - google.golang.org/protobuf
          - github.com/adhocore/gronx
          - golang.org/x/exp/slices
          - github.com/go-openapi/strfmt
          - github.com/gorilla/websocket
          - golang.org/x/exp/maps
          - github.com/pkg/errors
          - loca-templates-manager/
          - github.com/go-openapi/runtime/client
          - github.com/rs/zerolog
          - github.com/prometheus/client_golang/prometheus
      test:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/open-edge-platform
          - github.com/google/uuid
          - github.com/mennanov/fmutils
          - github.com/onosproject/onos-lib-go
          - github.com/labstack/echo/v4
          - github.com/grpc-ecosystem/go-grpc-middleware
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - github.com/go-openapi/strfmt
          - github.com/gorilla/websocket
          - github.com/golang-jwt/jwt/v5
          - github.com/rs/zerolog
  cyclop:
    # SDL requirements recommend a maximum cyclomatic complexity of 10
    max-complexity: 10
  misspell:
    locale: US
  lll:
    line-length: 130
    tab-width: 4
  funlen:
    lines: 100
    statements: 50
  exhaustive:
    default-signifies-exhaustive: true

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      # These 3 will detect many cases, but they do sense
      # if it's performance oriented code
      - hugeParam
      - rangeExprCopy
      - rangeValCopy
      - whyNoLint
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0

  max-same-issues: 0

  uniq-by-line: false

  # When set to `true` linter will analyze only new code which are
  # not committed or after some specific revision. This is a cool
  # feature when you're going to introduce linter into a big project.
  # But I prefer going gradually package by package.
  # So, it's set to `false` to scan all code.
  new: false

  fix: false

  exclude:
    - Error return value of `.*Write` is not checked

  exclude-dirs:
    - pkg/api/

linters-settings:
  errcheck:
    check-blank: false
    exclude-functions:
      - (net/http.ResponseWriter).Write

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
  sort-results: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
