// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// DeleteAPIV1SecretsCredentialPoliciesIDReader is a Reader for the DeleteAPIV1SecretsCredentialPoliciesID structure.
type DeleteAPIV1SecretsCredentialPoliciesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV1SecretsCredentialPoliciesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIV1SecretsCredentialPoliciesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewDeleteAPIV1SecretsCredentialPoliciesIDBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewDeleteAPIV1SecretsCredentialPoliciesIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewDeleteAPIV1SecretsCredentialPoliciesIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v1/secrets/credential-policies/{id}] DeleteAPIV1SecretsCredentialPoliciesID", response, response.Code())
	}
}

// NewDeleteAPIV1SecretsCredentialPoliciesIDOK creates a DeleteAPIV1SecretsCredentialPoliciesIDOK with default headers values
func NewDeleteAPIV1SecretsCredentialPoliciesIDOK() *DeleteAPIV1SecretsCredentialPoliciesIDOK {
	return &DeleteAPIV1SecretsCredentialPoliciesIDOK{}
}

/*
DeleteAPIV1SecretsCredentialPoliciesIDOK describes a response with status code 200, with default header values.

success
*/
type DeleteAPIV1SecretsCredentialPoliciesIDOK struct {
	Payload *model.DtoUpdateCredentialpoliciesResponse
}

// IsSuccess returns true when this delete Api v1 secrets credential policies Id o k response has a 2xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api v1 secrets credential policies Id o k response has a 3xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 secrets credential policies Id o k response has a 4xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 secrets credential policies Id o k response has a 5xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 secrets credential policies Id o k response a status code equal to that given
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api v1 secrets credential policies Id o k response
func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) Code() int {
	return 200
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdOK %s", 200, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdOK %s", 200, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) GetPayload() *model.DtoUpdateCredentialpoliciesResponse {
	return o.Payload
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoUpdateCredentialpoliciesResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1SecretsCredentialPoliciesIDBadRequest creates a DeleteAPIV1SecretsCredentialPoliciesIDBadRequest with default headers values
func NewDeleteAPIV1SecretsCredentialPoliciesIDBadRequest() *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest {
	return &DeleteAPIV1SecretsCredentialPoliciesIDBadRequest{}
}

/*
DeleteAPIV1SecretsCredentialPoliciesIDBadRequest describes a response with status code 400, with default header values.

bad request
*/
type DeleteAPIV1SecretsCredentialPoliciesIDBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this delete Api v1 secrets credential policies Id bad request response has a 2xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 secrets credential policies Id bad request response has a 3xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 secrets credential policies Id bad request response has a 4xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 secrets credential policies Id bad request response has a 5xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 secrets credential policies Id bad request response a status code equal to that given
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the delete Api v1 secrets credential policies Id bad request response
func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) Code() int {
	return 400
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdBadRequest %s", 400, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdBadRequest %s", 400, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1SecretsCredentialPoliciesIDUnauthorized creates a DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized with default headers values
func NewDeleteAPIV1SecretsCredentialPoliciesIDUnauthorized() *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized {
	return &DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized{}
}

/*
DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized describes a response with status code 401, with default header values.

auth fail
*/
type DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this delete Api v1 secrets credential policies Id unauthorized response has a 2xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 secrets credential policies Id unauthorized response has a 3xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 secrets credential policies Id unauthorized response has a 4xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v1 secrets credential policies Id unauthorized response has a 5xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v1 secrets credential policies Id unauthorized response a status code equal to that given
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the delete Api v1 secrets credential policies Id unauthorized response
func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) Code() int {
	return 401
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdUnauthorized %s", 401, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdUnauthorized %s", 401, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewDeleteAPIV1SecretsCredentialPoliciesIDInternalServerError creates a DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError with default headers values
func NewDeleteAPIV1SecretsCredentialPoliciesIDInternalServerError() *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError {
	return &DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError{}
}

/*
DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this delete Api v1 secrets credential policies Id internal server error response has a 2xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v1 secrets credential policies Id internal server error response has a 3xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v1 secrets credential policies Id internal server error response has a 4xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v1 secrets credential policies Id internal server error response has a 5xx status code
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this delete Api v1 secrets credential policies Id internal server error response a status code equal to that given
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the delete Api v1 secrets credential policies Id internal server error response
func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) Code() int {
	return 500
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdInternalServerError %s", 500, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v1/secrets/credential-policies/{id}][%d] deleteApiV1SecretsCredentialPoliciesIdInternalServerError %s", 500, payload)
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *DeleteAPIV1SecretsCredentialPoliciesIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
