# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/loca-metadata"
      - "/loca-onboarding"
      - "/loca-templates"
      - "/dm-manager"
    registries:
      - github
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    commit-message:
      prefix: "[gomod] "
    groups:
      dependencies:
        patterns:
         - "*"
