# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

CI 🤖:
  - changed-files:
      - any-glob-to-any-file: ".github/**"

root:
  - changed-files:
      - any-glob-to-any-file: "*"

loca-metadata:
  - changed-files:
    - any-glob-to-any-file: "loca-metadata/**"

loca-onboarding:
  - changed-files:
    - any-glob-to-any-file: "loca-onboarding/**"

loca-templates:
  - changed-files:
    - any-glob-to-any-file: "loca-templates/**"

loca-plugin:
  - changed-files:
      - any-glob-to-any-file: "loca-plugin/**"

dmt-manager:
- changed-files:
  - any-glob-to-any-file: "dmt-manager/**"
