---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    - depguard
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - godot  # Comment style warnings
    # - goheader  # Header checks
    - gomoddirectives
    - goprintffuncname
    # - gosec  # Security warnings
    - lll
    - misspell
    - mnd
    - nakedret
    # - nilerr  # Not available
    - nilnil
    # - noctx  # Context not always needed
    # - nolintlint  # Noisy
    # - prealloc  # Minor optimization
    - predeclared
    # - revive  # Too many style warnings
    # - stylecheck  # Style warnings
    # - tagliatelle  # Tag formatting
    # - testpackage  # Test package naming
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    errcheck:
      check-blank: false
      ignore: fmt:.*,io:EOF,io:Copy
      exclude-functions:
        - (net/http.ResponseWriter).Write
        - (*net/http.Request.Body).Close
    cyclop:
      max-complexity: 10
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - unnamedResult
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    lll:
      line-length: 130
      tab-width: 4
    misspell:
      locale: US
    mnd:
      ignored-functions:
        - os.Chmod
        - os.Mkdir
        - os.MkdirAll
        - os.OpenFile
        - os.WriteFile
    depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/google/uuid
            - github.com/onosproject/onos-lib-go
            - github.com/stretchr/testify/assert
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/mock
            - k8s.io/apimachinery/pkg/util/wait
            - k8s.io/client-go/util/retry
            - github.com/go-openapi/strfmt
            - github.com/go-openapi/runtime/client
            - github.com/go-openapi/runtime
            - github.com/prometheus/client_golang/prometheus
            - github.com/gorilla/mux
            - github.com/rs/zerolog
            - google.golang.org/grpc
            - google.golang.org/protobuf
          deny:
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/google/uuid
            - github.com/onosproject/onos-lib-go
            - github.com/open-edge-platform
            - github.com/stretchr/testify/require
            - github.com/stretchr/testify/assert
            - k8s.io/apimachinery/pkg/util/wait
            - k8s.io/client-go/util/retry
            - github.com/go-openapi/strfmt
            - github.com/go-openapi/runtime/client
            - github.com/go-openapi/runtime
            - github.com/gorilla/mux
            - github.com/rs/zerolog
            - google.golang.org/grpc
            - google.golang.org/protobuf
          deny:
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

issues:
  max-issues-per-linter: 0

  max-same-issues: 0

  uniq-by-line: false

  # When set to `true` linter will analyze only new code which are
  # not committed or after some specific revision. This is a cool
  # feature when you're going to introduce linter into a big project.
  # But I prefer going gradually package by package.
  # So, it's set to `false` to scan all code.
  new: false

  fix: false

  exclude:
    - Error return value of `.*Close` is not checked
    - Error return value of `.*Flush` is not checked
    - Error return value of `.*Write` is not checked
    - Error return value of `.*Stop` is not checked

  exclude-rules:
    - path: pkg/client/loca/loca_client_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: pkg/client/loca/loca_calls_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: pkg/client/loca/loca_util_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: pkg/client/loca/loca_testing_util_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: pkg/client/loca/loca_task_tracker_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: pkg/flags/flags_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: internal/manager/locarm_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: internal/handlers/host_reconciler_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
    - path: internal/handlers/instance_reconciler_test.go
      linters:
        # setting it as a separate package, loca_test, would not allow to
        # test unexported functions, which are main pillars of this codebase.
        - testpackage
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
  sort-results: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
