// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV1InventoryNetworkServicesParams creates a new GetAPIV1InventoryNetworkServicesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1InventoryNetworkServicesParams() *GetAPIV1InventoryNetworkServicesParams {
	return &GetAPIV1InventoryNetworkServicesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InventoryNetworkServicesParamsWithTimeout creates a new GetAPIV1InventoryNetworkServicesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1InventoryNetworkServicesParamsWithTimeout(timeout time.Duration) *GetAPIV1InventoryNetworkServicesParams {
	return &GetAPIV1InventoryNetworkServicesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1InventoryNetworkServicesParamsWithContext creates a new GetAPIV1InventoryNetworkServicesParams object
// with the ability to set a context for a request.
func NewGetAPIV1InventoryNetworkServicesParamsWithContext(ctx context.Context) *GetAPIV1InventoryNetworkServicesParams {
	return &GetAPIV1InventoryNetworkServicesParams{
		Context: ctx,
	}
}

// NewGetAPIV1InventoryNetworkServicesParamsWithHTTPClient creates a new GetAPIV1InventoryNetworkServicesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1InventoryNetworkServicesParamsWithHTTPClient(client *http.Client) *GetAPIV1InventoryNetworkServicesParams {
	return &GetAPIV1InventoryNetworkServicesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1InventoryNetworkServicesParams contains all the parameters to send to the API endpoint

	for the get API v1 inventory network services operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1InventoryNetworkServicesParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	/* ConnectionCheck.

	   filter by connectionCheck
	*/
	ConnectionCheck *bool

	/* FilterContains.

	   Returns data that contains a specific pattern. Within the same filter query, data matches the query if the value of any one of the specified attributes contains any one of the specified patterns. the following example will return data which city contains shzj001 or shzj002, or county contains shzj001 or shzj002, example: [{"attributes":"city,country","values":"shzj001,shzj002"}]

	   Default: "[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]"
	*/
	FilterContains *string

	/* FilterEquals.

	   Returns data that exactly matches a specific pattern. Within the same filter query, data matches the query if the value of any one of the specified attributes exactly matches any one of the specified patterns. the following example will return data which city exactly matches shzj001 or shzj002, or county exactly matches shzj001 or shzj002, example: [{"attributes":"city,country","values":"shzj001,shzj002"}]

	   Default: "[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]"
	*/
	FilterEquals *string

	/* FilterNotEquals.

	   Returns data that not matches a specific pattern. Within the same filter query, data matches the query if the value of any one of the specified attributes exactly matches any one of the specified patterns. the following example will return data which city not match shzj001 or shzj002, or county not match shzj001 or shzj002, example: [{"attributes":"city,country","values":"shzj001,shzj002"}]

	   Default: "[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]"
	*/
	FilterNotEquals *string

	/* Limit.

	    , example: 10

	   Default: 10
	*/
	Limit *int64

	/* Name.

	   filter by name
	*/
	Name *string

	/* Offset.

	   , example: 0
	*/
	Offset *int64

	/* ParentService.

	   filter by parentService
	*/
	ParentService *string

	/* PlatformType.

	   filter by platformType
	*/
	PlatformType *string

	/* Protocol.

	   filter by protocol
	*/
	Protocol *string

	/* Role.

	   filter by role
	*/
	Role *string

	/* ServiceAddress.

	   filter by serviceAddress
	*/
	ServiceAddress *string

	/* SiteAssociation.

	   filter by siteAssociation
	*/
	SiteAssociation *string

	/* Sort.

	   returns data that sorted by specific rules. The following example sorts data first by created_time in descending order and then by id in ascending order., example: ["created_time,desc","id,asc"]

	   Default: "[\"created_time,desc\",\"id,asc\"]"
	*/
	Sort *string

	/* Status.

	   filter by status
	*/
	Status *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 inventory network services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1InventoryNetworkServicesParams) WithDefaults() *GetAPIV1InventoryNetworkServicesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 inventory network services params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1InventoryNetworkServicesParams) SetDefaults() {
	var (
		filterContainsDefault = string("[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]")

		filterEqualsDefault = string("[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]")

		filterNotEqualsDefault = string("[{\"attributes\":\"city,country\",\"values\":\"shzj001,shzj002\"}]")

		limitDefault = int64(10)

		offsetDefault = int64(0)

		sortDefault = string("[\"created_time,desc\",\"id,asc\"]")
	)

	val := GetAPIV1InventoryNetworkServicesParams{
		FilterContains:  &filterContainsDefault,
		FilterEquals:    &filterEqualsDefault,
		FilterNotEquals: &filterNotEqualsDefault,
		Limit:           &limitDefault,
		Offset:          &offsetDefault,
		Sort:            &sortDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithTimeout(timeout time.Duration) *GetAPIV1InventoryNetworkServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithContext(ctx context.Context) *GetAPIV1InventoryNetworkServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithHTTPClient(client *http.Client) *GetAPIV1InventoryNetworkServicesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithAuthorization(authorization string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithConnectionCheck adds the connectionCheck to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithConnectionCheck(connectionCheck *bool) *GetAPIV1InventoryNetworkServicesParams {
	o.SetConnectionCheck(connectionCheck)
	return o
}

// SetConnectionCheck adds the connectionCheck to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetConnectionCheck(connectionCheck *bool) {
	o.ConnectionCheck = connectionCheck
}

// WithFilterContains adds the filterContains to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithFilterContains(filterContains *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetFilterContains(filterContains)
	return o
}

// SetFilterContains adds the filterContains to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetFilterContains(filterContains *string) {
	o.FilterContains = filterContains
}

// WithFilterEquals adds the filterEquals to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithFilterEquals(filterEquals *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetFilterEquals(filterEquals)
	return o
}

// SetFilterEquals adds the filterEquals to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetFilterEquals(filterEquals *string) {
	o.FilterEquals = filterEquals
}

// WithFilterNotEquals adds the filterNotEquals to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithFilterNotEquals(filterNotEquals *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetFilterNotEquals(filterNotEquals)
	return o
}

// SetFilterNotEquals adds the filterNotEquals to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetFilterNotEquals(filterNotEquals *string) {
	o.FilterNotEquals = filterNotEquals
}

// WithLimit adds the limit to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithLimit(limit *int64) *GetAPIV1InventoryNetworkServicesParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithName(name *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetName(name *string) {
	o.Name = name
}

// WithOffset adds the offset to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithOffset(offset *int64) *GetAPIV1InventoryNetworkServicesParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithParentService adds the parentService to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithParentService(parentService *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetParentService(parentService)
	return o
}

// SetParentService adds the parentService to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetParentService(parentService *string) {
	o.ParentService = parentService
}

// WithPlatformType adds the platformType to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithPlatformType(platformType *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetPlatformType(platformType)
	return o
}

// SetPlatformType adds the platformType to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetPlatformType(platformType *string) {
	o.PlatformType = platformType
}

// WithProtocol adds the protocol to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithProtocol(protocol *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetProtocol(protocol)
	return o
}

// SetProtocol adds the protocol to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetProtocol(protocol *string) {
	o.Protocol = protocol
}

// WithRole adds the role to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithRole(role *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetRole(role)
	return o
}

// SetRole adds the role to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetRole(role *string) {
	o.Role = role
}

// WithServiceAddress adds the serviceAddress to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithServiceAddress(serviceAddress *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetServiceAddress(serviceAddress)
	return o
}

// SetServiceAddress adds the serviceAddress to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetServiceAddress(serviceAddress *string) {
	o.ServiceAddress = serviceAddress
}

// WithSiteAssociation adds the siteAssociation to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithSiteAssociation(siteAssociation *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetSiteAssociation(siteAssociation)
	return o
}

// SetSiteAssociation adds the siteAssociation to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetSiteAssociation(siteAssociation *string) {
	o.SiteAssociation = siteAssociation
}

// WithSort adds the sort to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithSort(sort *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetSort(sort *string) {
	o.Sort = sort
}

// WithStatus adds the status to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) WithStatus(status *string) *GetAPIV1InventoryNetworkServicesParams {
	o.SetStatus(status)
	return o
}

// SetStatus adds the status to the get API v1 inventory network services params
func (o *GetAPIV1InventoryNetworkServicesParams) SetStatus(status *string) {
	o.Status = status
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InventoryNetworkServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if o.ConnectionCheck != nil {

		// query param connectionCheck
		var qrConnectionCheck bool

		if o.ConnectionCheck != nil {
			qrConnectionCheck = *o.ConnectionCheck
		}
		qConnectionCheck := swag.FormatBool(qrConnectionCheck)
		if qConnectionCheck != "" {

			if err := r.SetQueryParam("connectionCheck", qConnectionCheck); err != nil {
				return err
			}
		}
	}

	if o.FilterContains != nil {

		// query param filterContains
		var qrFilterContains string

		if o.FilterContains != nil {
			qrFilterContains = *o.FilterContains
		}
		qFilterContains := qrFilterContains
		if qFilterContains != "" {

			if err := r.SetQueryParam("filterContains", qFilterContains); err != nil {
				return err
			}
		}
	}

	if o.FilterEquals != nil {

		// query param filterEquals
		var qrFilterEquals string

		if o.FilterEquals != nil {
			qrFilterEquals = *o.FilterEquals
		}
		qFilterEquals := qrFilterEquals
		if qFilterEquals != "" {

			if err := r.SetQueryParam("filterEquals", qFilterEquals); err != nil {
				return err
			}
		}
	}

	if o.FilterNotEquals != nil {

		// query param filterNotEquals
		var qrFilterNotEquals string

		if o.FilterNotEquals != nil {
			qrFilterNotEquals = *o.FilterNotEquals
		}
		qFilterNotEquals := qrFilterNotEquals
		if qFilterNotEquals != "" {

			if err := r.SetQueryParam("filterNotEquals", qFilterNotEquals); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	if o.ParentService != nil {

		// query param parentService
		var qrParentService string

		if o.ParentService != nil {
			qrParentService = *o.ParentService
		}
		qParentService := qrParentService
		if qParentService != "" {

			if err := r.SetQueryParam("parentService", qParentService); err != nil {
				return err
			}
		}
	}

	if o.PlatformType != nil {

		// query param platformType
		var qrPlatformType string

		if o.PlatformType != nil {
			qrPlatformType = *o.PlatformType
		}
		qPlatformType := qrPlatformType
		if qPlatformType != "" {

			if err := r.SetQueryParam("platformType", qPlatformType); err != nil {
				return err
			}
		}
	}

	if o.Protocol != nil {

		// query param protocol
		var qrProtocol string

		if o.Protocol != nil {
			qrProtocol = *o.Protocol
		}
		qProtocol := qrProtocol
		if qProtocol != "" {

			if err := r.SetQueryParam("protocol", qProtocol); err != nil {
				return err
			}
		}
	}

	if o.Role != nil {

		// query param role
		var qrRole string

		if o.Role != nil {
			qrRole = *o.Role
		}
		qRole := qrRole
		if qRole != "" {

			if err := r.SetQueryParam("role", qRole); err != nil {
				return err
			}
		}
	}

	if o.ServiceAddress != nil {

		// query param serviceAddress
		var qrServiceAddress string

		if o.ServiceAddress != nil {
			qrServiceAddress = *o.ServiceAddress
		}
		qServiceAddress := qrServiceAddress
		if qServiceAddress != "" {

			if err := r.SetQueryParam("serviceAddress", qServiceAddress); err != nil {
				return err
			}
		}
	}

	if o.SiteAssociation != nil {

		// query param siteAssociation
		var qrSiteAssociation string

		if o.SiteAssociation != nil {
			qrSiteAssociation = *o.SiteAssociation
		}
		qSiteAssociation := qrSiteAssociation
		if qSiteAssociation != "" {

			if err := r.SetQueryParam("siteAssociation", qSiteAssociation); err != nil {
				return err
			}
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if o.Status != nil {

		// query param status
		var qrStatus string

		if o.Status != nil {
			qrStatus = *o.Status
		}
		qStatus := qrStatus
		if qStatus != "" {

			if err := r.SetQueryParam("status", qStatus); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
