// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV1InventoryCloudServicesMetadataRulesParams creates a new GetAPIV1InventoryCloudServicesMetadataRulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV1InventoryCloudServicesMetadataRulesParams() *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	return &GetAPIV1InventoryCloudServicesMetadataRulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithTimeout creates a new GetAPIV1InventoryCloudServicesMetadataRulesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithTimeout(timeout time.Duration) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	return &GetAPIV1InventoryCloudServicesMetadataRulesParams{
		timeout: timeout,
	}
}

// NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithContext creates a new GetAPIV1InventoryCloudServicesMetadataRulesParams object
// with the ability to set a context for a request.
func NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithContext(ctx context.Context) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	return &GetAPIV1InventoryCloudServicesMetadataRulesParams{
		Context: ctx,
	}
}

// NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithHTTPClient creates a new GetAPIV1InventoryCloudServicesMetadataRulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV1InventoryCloudServicesMetadataRulesParamsWithHTTPClient(client *http.Client) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	return &GetAPIV1InventoryCloudServicesMetadataRulesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV1InventoryCloudServicesMetadataRulesParams contains all the parameters to send to the API endpoint

	for the get API v1 inventory cloud services metadata rules operation.

	Typically these are written to a http.Request.
*/
type GetAPIV1InventoryCloudServicesMetadataRulesParams struct {

	/* Authorization.

	   Bearer access token
	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v1 inventory cloud services metadata rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WithDefaults() *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v1 inventory cloud services metadata rules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WithTimeout(timeout time.Duration) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WithContext(ctx context.Context) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WithHTTPClient(client *http.Client) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WithAuthorization(authorization string) *GetAPIV1InventoryCloudServicesMetadataRulesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the get API v1 inventory cloud services metadata rules params
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV1InventoryCloudServicesMetadataRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
