// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// NewPostAPIV1InventoryIPRangesParams creates a new PostAPIV1InventoryIPRangesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1InventoryIPRangesParams() *PostAPIV1InventoryIPRangesParams {
	return &PostAPIV1InventoryIPRangesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1InventoryIPRangesParamsWithTimeout creates a new PostAPIV1InventoryIPRangesParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1InventoryIPRangesParamsWithTimeout(timeout time.Duration) *PostAPIV1InventoryIPRangesParams {
	return &PostAPIV1InventoryIPRangesParams{
		timeout: timeout,
	}
}

// NewPostAPIV1InventoryIPRangesParamsWithContext creates a new PostAPIV1InventoryIPRangesParams object
// with the ability to set a context for a request.
func NewPostAPIV1InventoryIPRangesParamsWithContext(ctx context.Context) *PostAPIV1InventoryIPRangesParams {
	return &PostAPIV1InventoryIPRangesParams{
		Context: ctx,
	}
}

// NewPostAPIV1InventoryIPRangesParamsWithHTTPClient creates a new PostAPIV1InventoryIPRangesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1InventoryIPRangesParamsWithHTTPClient(client *http.Client) *PostAPIV1InventoryIPRangesParams {
	return &PostAPIV1InventoryIPRangesParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1InventoryIPRangesParams contains all the parameters to send to the API endpoint

	for the post API v1 inventory IP ranges operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1InventoryIPRangesParams struct {

	/* Authorization.

	   Bearer access token
	*/
	Authorization string

	/* Body.

	   Array of IP range creation requests
	*/
	Body []*model.DtoIPRangeCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 inventory IP ranges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1InventoryIPRangesParams) WithDefaults() *PostAPIV1InventoryIPRangesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 inventory IP ranges params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1InventoryIPRangesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) WithTimeout(timeout time.Duration) *PostAPIV1InventoryIPRangesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) WithContext(ctx context.Context) *PostAPIV1InventoryIPRangesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) WithHTTPClient(client *http.Client) *PostAPIV1InventoryIPRangesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) WithAuthorization(authorization string) *PostAPIV1InventoryIPRangesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) WithBody(body []*model.DtoIPRangeCreateRequest) *PostAPIV1InventoryIPRangesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v1 inventory IP ranges params
func (o *PostAPIV1InventoryIPRangesParams) SetBody(body []*model.DtoIPRangeCreateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1InventoryIPRangesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
