// Code generated by go-swagger; DO NOT EDIT.

package inventory

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// PostAPIV1InventoryCloudServicesUpdateReader is a Reader for the PostAPIV1InventoryCloudServicesUpdate structure.
type PostAPIV1InventoryCloudServicesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1InventoryCloudServicesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1InventoryCloudServicesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1InventoryCloudServicesUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1InventoryCloudServicesUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewPostAPIV1InventoryCloudServicesUpdateNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1InventoryCloudServicesUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/inventory/cloud-services/update] PostAPIV1InventoryCloudServicesUpdate", response, response.Code())
	}
}

// NewPostAPIV1InventoryCloudServicesUpdateOK creates a PostAPIV1InventoryCloudServicesUpdateOK with default headers values
func NewPostAPIV1InventoryCloudServicesUpdateOK() *PostAPIV1InventoryCloudServicesUpdateOK {
	return &PostAPIV1InventoryCloudServicesUpdateOK{}
}

/*
PostAPIV1InventoryCloudServicesUpdateOK describes a response with status code 200, with default header values.

Cloud service updated successfully
*/
type PostAPIV1InventoryCloudServicesUpdateOK struct {
	Payload *model.DtoResponseCUD
}

// IsSuccess returns true when this post Api v1 inventory cloud services update o k response has a 2xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 inventory cloud services update o k response has a 3xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 inventory cloud services update o k response has a 4xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 inventory cloud services update o k response has a 5xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 inventory cloud services update o k response a status code equal to that given
func (o *PostAPIV1InventoryCloudServicesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 inventory cloud services update o k response
func (o *PostAPIV1InventoryCloudServicesUpdateOK) Code() int {
	return 200
}

func (o *PostAPIV1InventoryCloudServicesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateOK %s", 200, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateOK %s", 200, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateOK) GetPayload() *model.DtoResponseCUD {
	return o.Payload
}

func (o *PostAPIV1InventoryCloudServicesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoResponseCUD)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1InventoryCloudServicesUpdateBadRequest creates a PostAPIV1InventoryCloudServicesUpdateBadRequest with default headers values
func NewPostAPIV1InventoryCloudServicesUpdateBadRequest() *PostAPIV1InventoryCloudServicesUpdateBadRequest {
	return &PostAPIV1InventoryCloudServicesUpdateBadRequest{}
}

/*
PostAPIV1InventoryCloudServicesUpdateBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type PostAPIV1InventoryCloudServicesUpdateBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 inventory cloud services update bad request response has a 2xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 inventory cloud services update bad request response has a 3xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 inventory cloud services update bad request response has a 4xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 inventory cloud services update bad request response has a 5xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 inventory cloud services update bad request response a status code equal to that given
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 inventory cloud services update bad request response
func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateBadRequest %s", 400, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateBadRequest %s", 400, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1InventoryCloudServicesUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1InventoryCloudServicesUpdateUnauthorized creates a PostAPIV1InventoryCloudServicesUpdateUnauthorized with default headers values
func NewPostAPIV1InventoryCloudServicesUpdateUnauthorized() *PostAPIV1InventoryCloudServicesUpdateUnauthorized {
	return &PostAPIV1InventoryCloudServicesUpdateUnauthorized{}
}

/*
PostAPIV1InventoryCloudServicesUpdateUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type PostAPIV1InventoryCloudServicesUpdateUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 inventory cloud services update unauthorized response has a 2xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 inventory cloud services update unauthorized response has a 3xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 inventory cloud services update unauthorized response has a 4xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 inventory cloud services update unauthorized response has a 5xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 inventory cloud services update unauthorized response a status code equal to that given
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 inventory cloud services update unauthorized response
func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateUnauthorized %s", 401, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateUnauthorized %s", 401, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1InventoryCloudServicesUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1InventoryCloudServicesUpdateNotFound creates a PostAPIV1InventoryCloudServicesUpdateNotFound with default headers values
func NewPostAPIV1InventoryCloudServicesUpdateNotFound() *PostAPIV1InventoryCloudServicesUpdateNotFound {
	return &PostAPIV1InventoryCloudServicesUpdateNotFound{}
}

/*
PostAPIV1InventoryCloudServicesUpdateNotFound describes a response with status code 404, with default header values.

Cloud service not found
*/
type PostAPIV1InventoryCloudServicesUpdateNotFound struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 inventory cloud services update not found response has a 2xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 inventory cloud services update not found response has a 3xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 inventory cloud services update not found response has a 4xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 inventory cloud services update not found response has a 5xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 inventory cloud services update not found response a status code equal to that given
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the post Api v1 inventory cloud services update not found response
func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) Code() int {
	return 404
}

func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateNotFound %s", 404, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateNotFound %s", 404, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1InventoryCloudServicesUpdateNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1InventoryCloudServicesUpdateInternalServerError creates a PostAPIV1InventoryCloudServicesUpdateInternalServerError with default headers values
func NewPostAPIV1InventoryCloudServicesUpdateInternalServerError() *PostAPIV1InventoryCloudServicesUpdateInternalServerError {
	return &PostAPIV1InventoryCloudServicesUpdateInternalServerError{}
}

/*
PostAPIV1InventoryCloudServicesUpdateInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type PostAPIV1InventoryCloudServicesUpdateInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 inventory cloud services update internal server error response has a 2xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 inventory cloud services update internal server error response has a 3xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 inventory cloud services update internal server error response has a 4xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 inventory cloud services update internal server error response has a 5xx status code
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 inventory cloud services update internal server error response a status code equal to that given
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 inventory cloud services update internal server error response
func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateInternalServerError %s", 500, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/inventory/cloud-services/update][%d] postApiV1InventoryCloudServicesUpdateInternalServerError %s", 500, payload)
}

func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1InventoryCloudServicesUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
