# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
version: "2"
run:
  go: ""
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint_report.html
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - decorder
    - depguard
    - dogsled
    - durationcheck
    - errcheck  # Re-enabled but with proper exclusions
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - copyloopvar
    - forbidigo  # Re-enabled after fixing fmt.Println
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    # - gochecknoglobals  # Disabled - flags and package-level constants are idiomatic Go
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    # - godox  # Disabled - TODO comments are valuable documentation
    - gomoddirectives
    - goprintffuncname
    - gosmopolitan
    - grouper
    - intrange  # Re-enabled after fixing loop
    - lll
    - loggercheck
    - maintidx
    - mirror
    - misspell
    - mnd
    - musttag
    - nakedret
    - nilnil
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - sloglint
    - spancheck
    - staticcheck  # Re-enabled after fixing De Morgan's law
    # - tagliatelle  # Disabled - test structs match external API format
    - testableexamples
    # - testifylint  # Disabled - assert.NoError is acceptable in tests
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      max-complexity: 10
    depguard:
      rules:
        main:
          files:
            - $all
            - "!$test"
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/prometheus
            - github.com/rs/zerolog
            - k8s.io/apimachinery/pkg
            - github.com/google/uuid
            - google.golang.org/grpc
            - google.golang.org/grpc/codes
            - google.golang.org/grpc/reflection
            - google.golang.org/protobuf/proto
            - google.golang.org/protobuf/types/known/fieldmaskpb
        test:
          files:
            - "$test"
          allow:
            - $gostd
            - github.com/open-edge-platform
            - github.com/prometheus
            - github.com/stretchr/testify
            - github.com/google/uuid
            - github.com/rs/zerolog
            - k8s.io/apimachinery/pkg
            - google.golang.org/grpc
            - google.golang.org/grpc/codes
            - google.golang.org/grpc/status
            - google.golang.org/grpc/credentials/insecure
            - google.golang.org/protobuf/types/known/fieldmaskpb
    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow _ = for intentional ignoring
      exclude-functions:
        - io/ioutil.ReadFile
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - (*github.com/open-edge-platform/infra-external/dm-manager/pkg/grpc.DMHandler).Start
    exhaustive:
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 50
    gocritic:
      disabled-checks:
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - whyNoLint
        - importShadow  # Disabled as it's too noisy in test files
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gomoddirectives:
      replace-allow-list:
        - github.com/open-edge-platform/infra-external/loca-onboarding/v2
      replace-local: true
    govet:
      enable:
        - shadow
    lll:
      line-length: 130
      tab-width: 4
    misspell:
      locale: US
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          avro: snake
          bson: camel
          json: snake
          mapstructure: kebab
          xml: camel
          yaml: snake
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  fix: false
  exclude-rules:
    - linters:
        - testpackage
      path: pkg/tenant/controller_test.go
    - linters:
        - testpackage
      path: pkg/tenant/utils_test.go
    - linters:
        - testpackage
      path: pkg/device/device_test.go
    - linters:
        - intrange
      path: pkg/grpc/grpc_server_start_test.go
    - linters:
        - staticcheck
      path: cmd/dm-manager.go
    # Exclude errcheck for intentionally ignored Close() calls in defers with blank identifier
    - linters:
        - errcheck
      text: "Error return value of .* is not checked"
    # Exclude global variables that are loggers
    - linters:
        - gochecknoglobals
      text: "(log|zlog|loggerName|name) is a global variable"
    # Exclude global variables that are flag definitions and channels in cmd
    - linters:
        - gochecknoglobals
      path: cmd/
    # Exclude global variables that are mapping constants
    - linters:
        - gochecknoglobals
      path: pkg/device/device.go
    # Exclude global variables that are status constants
    - linters:
        - gochecknoglobals
      path: pkg/status/status.go
    # Exclude global variables in grpc server
    - linters:
        - gochecknoglobals
      path: pkg/grpc/
    # Exclude TODO/FIXME comments as they indicate future work
    - linters:
        - godox
    # Exclude tagliatelle for test structs matching external API format
    - linters:
        - tagliatelle
      path: _test\.go$
    # Exclude testifylint for legacy test patterns that are acceptable
    - linters:
        - testifylint
    - path: (.+)\.go$
      text: Error return value of `.*Close` is not checked
    - path: (.+)\.go$
      text: Error return value of `.*Flush` is not checked
    - path: (.+)\.go$
      text: Error return value of `.*Write` is not checked
    - path: (.+)\.go$
      text: Error return value of `.*Stop` is not checked
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
    gofumpt:
      module-path: github.com/open-edge-platform/infra-external/dm-manager
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
