# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
template: testify
packages:
  github.com/open-edge-platform/infra-external/dm-manager/pkg/api/mps:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks.go"
      pkgname: "mps"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ClientWithResponsesInterface:
  github.com/open-edge-platform/infra-external/dm-manager/pkg/api/rps:
    config:
      dir: "{{.InterfaceDir}}"
      filename: "mocks.go"
      pkgname: "rps"
      structname: "Mock{{.InterfaceName}}"
    interfaces:
      ClientWithResponsesInterface:
