// Code generated by go-swagger; DO NOT EDIT.

package deployments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// PostAPIV1DeploymentsReader is a Reader for the PostAPIV1Deployments structure.
type PostAPIV1DeploymentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1DeploymentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1DeploymentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1DeploymentsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1DeploymentsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1DeploymentsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/deployments] PostAPIV1Deployments", response, response.Code())
	}
}

// NewPostAPIV1DeploymentsOK creates a PostAPIV1DeploymentsOK with default headers values
func NewPostAPIV1DeploymentsOK() *PostAPIV1DeploymentsOK {
	return &PostAPIV1DeploymentsOK{}
}

/*
PostAPIV1DeploymentsOK describes a response with status code 200, with default header values.

success
*/
type PostAPIV1DeploymentsOK struct {
	Payload *model.DtoResponseBase
}

// IsSuccess returns true when this post Api v1 deployments o k response has a 2xx status code
func (o *PostAPIV1DeploymentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 deployments o k response has a 3xx status code
func (o *PostAPIV1DeploymentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployments o k response has a 4xx status code
func (o *PostAPIV1DeploymentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployments o k response has a 5xx status code
func (o *PostAPIV1DeploymentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployments o k response a status code equal to that given
func (o *PostAPIV1DeploymentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 deployments o k response
func (o *PostAPIV1DeploymentsOK) Code() int {
	return 200
}

func (o *PostAPIV1DeploymentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsOK %s", 200, payload)
}

func (o *PostAPIV1DeploymentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsOK %s", 200, payload)
}

func (o *PostAPIV1DeploymentsOK) GetPayload() *model.DtoResponseBase {
	return o.Payload
}

func (o *PostAPIV1DeploymentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoResponseBase)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentsBadRequest creates a PostAPIV1DeploymentsBadRequest with default headers values
func NewPostAPIV1DeploymentsBadRequest() *PostAPIV1DeploymentsBadRequest {
	return &PostAPIV1DeploymentsBadRequest{}
}

/*
PostAPIV1DeploymentsBadRequest describes a response with status code 400, with default header values.

bad request
*/
type PostAPIV1DeploymentsBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployments bad request response has a 2xx status code
func (o *PostAPIV1DeploymentsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployments bad request response has a 3xx status code
func (o *PostAPIV1DeploymentsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployments bad request response has a 4xx status code
func (o *PostAPIV1DeploymentsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployments bad request response has a 5xx status code
func (o *PostAPIV1DeploymentsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployments bad request response a status code equal to that given
func (o *PostAPIV1DeploymentsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 deployments bad request response
func (o *PostAPIV1DeploymentsBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1DeploymentsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentsBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentsUnauthorized creates a PostAPIV1DeploymentsUnauthorized with default headers values
func NewPostAPIV1DeploymentsUnauthorized() *PostAPIV1DeploymentsUnauthorized {
	return &PostAPIV1DeploymentsUnauthorized{}
}

/*
PostAPIV1DeploymentsUnauthorized describes a response with status code 401, with default header values.

auth fail
*/
type PostAPIV1DeploymentsUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployments unauthorized response has a 2xx status code
func (o *PostAPIV1DeploymentsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployments unauthorized response has a 3xx status code
func (o *PostAPIV1DeploymentsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployments unauthorized response has a 4xx status code
func (o *PostAPIV1DeploymentsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployments unauthorized response has a 5xx status code
func (o *PostAPIV1DeploymentsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployments unauthorized response a status code equal to that given
func (o *PostAPIV1DeploymentsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 deployments unauthorized response
func (o *PostAPIV1DeploymentsUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1DeploymentsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentsUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentsInternalServerError creates a PostAPIV1DeploymentsInternalServerError with default headers values
func NewPostAPIV1DeploymentsInternalServerError() *PostAPIV1DeploymentsInternalServerError {
	return &PostAPIV1DeploymentsInternalServerError{}
}

/*
PostAPIV1DeploymentsInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type PostAPIV1DeploymentsInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployments internal server error response has a 2xx status code
func (o *PostAPIV1DeploymentsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployments internal server error response has a 3xx status code
func (o *PostAPIV1DeploymentsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployments internal server error response has a 4xx status code
func (o *PostAPIV1DeploymentsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployments internal server error response has a 5xx status code
func (o *PostAPIV1DeploymentsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 deployments internal server error response a status code equal to that given
func (o *PostAPIV1DeploymentsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 deployments internal server error response
func (o *PostAPIV1DeploymentsInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1DeploymentsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployments][%d] postApiV1DeploymentsInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentsInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
