---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version: "2"

run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly
  go: ""

linters:
  disable-all: true
  enable:
    - errcheck
    - staticcheck
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - cyclop
    # - depguard  # Many import violations
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    # - funlen  # Main function is too long
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    # - gosec  # Too many security warnings
    - goprintffuncname
    # - lll  # Many long lines in comments
    - misspell
    - mnd
    - nakedret
    - nilnil
    # - noctx  # Context not always needed
    # - nolintlint  # Noisy
    # - prealloc  # Minor optimization
    - predeclared
    # - revive  # Too many style warnings
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - whitespace
  settings:
    cyclop:
      # SDL requirements dictate a maximum cyclomatic complexity of 10
      max-complexity: 10
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        # These 3 will detect many cases, but they do sense
        # if it's performance oriented code
        - hugeParam
        - rangeExprCopy
        - rangeValCopy
        - unnamedResult
    exhaustive:
      default-signifies-exhaustive: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0

  max-same-issues: 0

  uniq-by-line: false

  # When set to `true` linter will analyze only new code which are
  # not committed or after some specific revision. This is a cool
  # feature when you're going to introduce linter into a big project.
  # But I prefer going gradually package by package.
  # So, it's set to `false` to scan all code.
  new: false

  fix: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
        path: cmd/locametamgr.go
      - linters:
          - lll
        path: internal/handlers/site_reconciler.go
      - linters:
          - lll
        path: internal/manager/locamm.go
      - linters:
          - lll
        path: pkg/util/util.go
      - linters:
          - testpackage
        path: internal/handlers/site_reconciler_test.go
      - linters:
          - testpackage
        path: pkg/util/util_test.go
      - linters:
          - testpackage
        path: internal/util/util_test.go
      - linters:
          - testpackage
        path: internal/manager/locamm_test.go
      - linters:
          - testpackage
        path: internal/manager/loca_calls_test.go
      - path: (.+)\.go$
        text: Error return value of `.*Close` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Flush` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Write` is not checked
      - path: (.+)\.go$
        text: Error return value of `.*Stop` is not checked
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
    html:
      path: out/golangci-lint.html
    junit-xml:
      path: out/golangci-lint.xml
  sort-results: true
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/open-edge-platform)
  exclusions:
    generated: lax
    paths:
      - pkg/api/
      - third_party$
      - builtin$
      - examples$
