// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1PluginsParams creates a new PostAPIV1PluginsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1PluginsParams() *PostAPIV1PluginsParams {
	return &PostAPIV1PluginsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1PluginsParamsWithTimeout creates a new PostAPIV1PluginsParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1PluginsParamsWithTimeout(timeout time.Duration) *PostAPIV1PluginsParams {
	return &PostAPIV1PluginsParams{
		timeout: timeout,
	}
}

// NewPostAPIV1PluginsParamsWithContext creates a new PostAPIV1PluginsParams object
// with the ability to set a context for a request.
func NewPostAPIV1PluginsParamsWithContext(ctx context.Context) *PostAPIV1PluginsParams {
	return &PostAPIV1PluginsParams{
		Context: ctx,
	}
}

// NewPostAPIV1PluginsParamsWithHTTPClient creates a new PostAPIV1PluginsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1PluginsParamsWithHTTPClient(client *http.Client) *PostAPIV1PluginsParams {
	return &PostAPIV1PluginsParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1PluginsParams contains all the parameters to send to the API endpoint

	for the post API v1 plugins operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1PluginsParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 plugins params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1PluginsParams) WithDefaults() *PostAPIV1PluginsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 plugins params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1PluginsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) WithTimeout(timeout time.Duration) *PostAPIV1PluginsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) WithContext(ctx context.Context) *PostAPIV1PluginsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) WithHTTPClient(client *http.Client) *PostAPIV1PluginsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) WithAuthorization(authorization *string) *PostAPIV1PluginsParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 plugins params
func (o *PostAPIV1PluginsParams) SetAuthorization(authorization *string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1PluginsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Authorization != nil {

		// header param Authorization
		if err := r.SetHeaderParam("Authorization", *o.Authorization); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
