// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoUpdateTemplateInstanceInfo dto update template instance info
//
// swagger:model dto.UpdateTemplateInstanceInfo
type DtoUpdateTemplateInstanceInfo struct {

	// the flavor options of the instance info
	FlavorOptions struct {
		DtoTemplateFlavorOptions
	} `json:"flavorOptions,omitempty"`

	// the name template of the instance info (e.g., ubuntu{{#}}.{{site_code}}.{{province}}.{{country}}.customer.com)
	Name string `json:"name,omitempty"`
}

// Validate validates this dto update template instance info
func (m *DtoUpdateTemplateInstanceInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFlavorOptions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoUpdateTemplateInstanceInfo) validateFlavorOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.FlavorOptions) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this dto update template instance info based on the context it is used
func (m *DtoUpdateTemplateInstanceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFlavorOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoUpdateTemplateInstanceInfo) contextValidateFlavorOptions(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *DtoUpdateTemplateInstanceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoUpdateTemplateInstanceInfo) UnmarshalBinary(b []byte) error {
	var res DtoUpdateTemplateInstanceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
