// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoNetwork dto network
//
// swagger:model dto.Network
type DtoNetwork struct {

	// address end
	AddressEnd string `json:"addressEnd,omitempty"`

	// address start
	AddressStart string `json:"addressStart,omitempty"`

	// flavor extra i ps
	FlavorExtraIPs []string `json:"flavorExtraIPs"`

	// gateway
	Gateway string `json:"gateway,omitempty"`

	// netmask
	Netmask string `json:"netmask,omitempty"`

	// prefix
	Prefix int64 `json:"prefix,omitempty"`

	// subnet
	Subnet string `json:"subnet,omitempty"`

	// vlan
	Vlan string `json:"vlan,omitempty"`
}

// Validate validates this dto network
func (m *DtoNetwork) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto network based on context it is used
func (m *DtoNetwork) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoNetwork) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoNetwork) UnmarshalBinary(b []byte) error {
	var res DtoNetwork
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
