// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DtoInstanceInfo dto instance info
//
// swagger:model dto.InstanceInfo
type DtoInstanceInfo struct {

	// 1. if the flavor is os type, only the first one will be used. If not input any device, will auto select suitable device from device list.
	Devices []string `json:"devices"`

	// site ID
	// Required: true
	SiteID *string `json:"siteID"`
}

// Validate validates this dto instance info
func (m *DtoInstanceInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSiteID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoInstanceInfo) validateSiteID(formats strfmt.Registry) error {

	if err := validate.Required("siteID", "body", m.SiteID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this dto instance info based on context it is used
func (m *DtoInstanceInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoInstanceInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoInstanceInfo) UnmarshalBinary(b []byte) error {
	var res DtoInstanceInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
