// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoCertSANs dto cert s a ns
//
// swagger:model dto.CertSANs
type DtoCertSANs struct {

	// dns list
	DNSList []string `json:"dns_list"`

	// email list
	EmailList []string `json:"email_list"`

	// ip list
	IPList []string `json:"ip_list"`

	// uri list
	URIList []string `json:"uri_list"`
}

// Validate validates this dto cert s a ns
func (m *DtoCertSANs) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto cert s a ns based on context it is used
func (m *DtoCertSANs) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoCertSANs) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoCertSANs) UnmarshalBinary(b []byte) error {
	var res DtoCertSANs
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
