// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDeployInstancesRequest dto deploy instances request
//
// swagger:model dto.DeployInstancesRequest
type DtoDeployInstancesRequest struct {

	// instances name
	InstancesName []string `json:"instances_name"`
}

// Validate validates this dto deploy instances request
func (m *DtoDeployInstancesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto deploy instances request based on context it is used
func (m *DtoDeployInstancesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDeployInstancesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDeployInstancesRequest) UnmarshalBinary(b []byte) error {
	var res DtoDeployInstancesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
