// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoAddDeviceParams dto add device params
//
// swagger:model dto.AddDeviceParams
type DtoAddDeviceParams struct {

	// gateway
	Gateway string `json:"gateway,omitempty"`

	// register info
	RegisterInfo []*DtoAddDeviceDTO `json:"register_info"`
}

// Validate validates this dto add device params
func (m *DtoAddDeviceParams) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRegisterInfo(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoAddDeviceParams) validateRegisterInfo(formats strfmt.Registry) error {
	if swag.IsZero(m.RegisterInfo) { // not required
		return nil
	}

	for i := 0; i < len(m.RegisterInfo); i++ {
		if swag.IsZero(m.RegisterInfo[i]) { // not required
			continue
		}

		if m.RegisterInfo[i] != nil {
			if err := m.RegisterInfo[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("register_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("register_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this dto add device params based on the context it is used
func (m *DtoAddDeviceParams) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateRegisterInfo(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DtoAddDeviceParams) contextValidateRegisterInfo(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RegisterInfo); i++ {

		if m.RegisterInfo[i] != nil {

			if swag.IsZero(m.RegisterInfo[i]) { // not required
				return nil
			}

			if err := m.RegisterInfo[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("register_info" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("register_info" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *DtoAddDeviceParams) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoAddDeviceParams) UnmarshalBinary(b []byte) error {
	var res DtoAddDeviceParams
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
