// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDeviceCredential dto device credential
//
// swagger:model dto.DeviceCredential
type DtoDeviceCredential struct {

	// credential policy ID
	CredentialPolicyID string `json:"credentialPolicyID,omitempty"`

	// current password
	CurrentPassword string `json:"currentPassword,omitempty"`

	// new password
	NewPassword string `json:"newPassword,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this dto device credential
func (m *DtoDeviceCredential) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto device credential based on context it is used
func (m *DtoDeviceCredential) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDeviceCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDeviceCredential) UnmarshalBinary(b []byte) error {
	var res DtoDeviceCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
