// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoUserResponseData dto user response data
//
// swagger:model dto.UserResponseData
type DtoUserResponseData struct {

	// created time
	CreatedTime string `json:"created_time,omitempty"`

	// expiration period
	ExpirationPeriod string `json:"expiration_period,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// password
	Password string `json:"password,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// update time
	UpdateTime string `json:"update_time,omitempty"`
}

// Validate validates this dto user response data
func (m *DtoUserResponseData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto user response data based on context it is used
func (m *DtoUserResponseData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoUserResponseData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoUserResponseData) UnmarshalBinary(b []byte) error {
	var res DtoUserResponseData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
