// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoCondition dto condition
//
// swagger:model dto.Condition
type DtoCondition struct {

	// Field the condition applies to
	Field string `json:"field,omitempty"`

	// Comparison operator (e.g., "==", ">", "<=", etc.)
	Operator string `json:"operator,omitempty"`

	// Value to compare against
	Value any `json:"value,omitempty"`
}

// Validate validates this dto condition
func (m *DtoCondition) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto condition based on context it is used
func (m *DtoCondition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoCondition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoCondition) UnmarshalBinary(b []byte) error {
	var res DtoCondition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
