// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoPlugin dto plugin
//
// swagger:model dto.Plugin
type DtoPlugin struct {

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// flavor
	Flavor string `json:"flavor,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// index
	Index string `json:"index,omitempty"`

	// is built in
	IsBuiltIn bool `json:"isBuiltIn,omitempty"`

	// is deleted
	IsDeleted bool `json:"isDeleted,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// options
	Options map[string]any `json:"options,omitempty"`

	// support os deploy
	SupportOsDeploy bool `json:"supportOsDeploy,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// vendor
	Vendor string `json:"vendor,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this dto plugin
func (m *DtoPlugin) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto plugin based on context it is used
func (m *DtoPlugin) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoPlugin) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoPlugin) UnmarshalBinary(b []byte) error {
	var res DtoPlugin
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
