// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoDeviceUpdateResponse dto device update response
//
// swagger:model dto.DeviceUpdateResponse
type DtoDeviceUpdateResponse struct {

	// message
	Message string `json:"message,omitempty"`

	// status code
	StatusCode int64 `json:"statusCode,omitempty"`
}

// Validate validates this dto device update response
func (m *DtoDeviceUpdateResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto device update response based on context it is used
func (m *DtoDeviceUpdateResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoDeviceUpdateResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoDeviceUpdateResponse) UnmarshalBinary(b []byte) error {
	var res DtoDeviceUpdateResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
