// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DtoCreateCredentialpolicies dto create credentialpolicies
//
// swagger:model dto.CreateCredentialpolicies
type DtoCreateCredentialpolicies struct {

	// count
	Count int64 `json:"count,omitempty"`

	// next
	Next string `json:"next,omitempty"`

	// previous
	Previous string `json:"previous,omitempty"`

	// results
	Results []string `json:"results"`
}

// Validate validates this dto create credentialpolicies
func (m *DtoCreateCredentialpolicies) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this dto create credentialpolicies based on context it is used
func (m *DtoCreateCredentialpolicies) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DtoCreateCredentialpolicies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DtoCreateCredentialpolicies) UnmarshalBinary(b []byte) error {
	var res DtoCreateCredentialpolicies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
