// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary hpcgitlab labs lenovo com loc backend cmd api models instance summary
//
// swagger:model hpcgitlab_labs_lenovo_com_loc_backend_cmd_api_models.InstanceSummary
type HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary struct {

	// cloud services
	CloudServices map[string][]string `json:"cloudServices,omitempty"`

	// hardware details
	HardwareDetails []*HpcgitlabLabsLenovoComLocBackendCmdAPIModelsHardwareDetail `json:"hardwareDetails"`

	// instance name
	InstanceName string `json:"instanceName,omitempty"`

	// network details
	NetworkDetails []*HpcgitlabLabsLenovoComLocBackendCmdAPIModelsNetworkDetail `json:"networkDetails"`

	// network services
	NetworkServices map[string][]string `json:"networkServices,omitempty"`

	// site name
	SiteName string `json:"siteName,omitempty"`
}

// Validate validates this hpcgitlab labs lenovo com loc backend cmd api models instance summary
func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHardwareDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNetworkDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) validateHardwareDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.HardwareDetails) { // not required
		return nil
	}

	for i := 0; i < len(m.HardwareDetails); i++ {
		if swag.IsZero(m.HardwareDetails[i]) { // not required
			continue
		}

		if m.HardwareDetails[i] != nil {
			if err := m.HardwareDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hardwareDetails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hardwareDetails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) validateNetworkDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.NetworkDetails) { // not required
		return nil
	}

	for i := 0; i < len(m.NetworkDetails); i++ {
		if swag.IsZero(m.NetworkDetails[i]) { // not required
			continue
		}

		if m.NetworkDetails[i] != nil {
			if err := m.NetworkDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkDetails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkDetails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this hpcgitlab labs lenovo com loc backend cmd api models instance summary based on the context it is used
func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHardwareDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateNetworkDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) contextValidateHardwareDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.HardwareDetails); i++ {

		if m.HardwareDetails[i] != nil {

			if swag.IsZero(m.HardwareDetails[i]) { // not required
				return nil
			}

			if err := m.HardwareDetails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hardwareDetails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hardwareDetails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) contextValidateNetworkDetails(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.NetworkDetails); i++ {

		if m.NetworkDetails[i] != nil {

			if swag.IsZero(m.NetworkDetails[i]) { // not required
				return nil
			}

			if err := m.NetworkDetails[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("networkDetails" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("networkDetails" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary) UnmarshalBinary(b []byte) error {
	var res HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
