// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsNetworkSettings models network settings
//
// swagger:model models.NetworkSettings
type ModelsNetworkSettings struct {

	// ipv4 addr
	IPV4Addr string `json:"ipv4Addr,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// netmask
	Netmask int64 `json:"netmask,omitempty"`

	// nic
	Nic string `json:"nic,omitempty"`
}

// Validate validates this models network settings
func (m *ModelsNetworkSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models network settings based on context it is used
func (m *ModelsNetworkSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsNetworkSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsNetworkSettings) UnmarshalBinary(b []byte) error {
	var res ModelsNetworkSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
