// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsRemoveInstancesRequest models remove instances request
//
// swagger:model models.RemoveInstancesRequest
type ModelsRemoveInstancesRequest struct {

	// ids
	Ids []string `json:"ids"`
}

// Validate validates this models remove instances request
func (m *ModelsRemoveInstancesRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this models remove instances request based on context it is used
func (m *ModelsRemoveInstancesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelsRemoveInstancesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsRemoveInstancesRequest) UnmarshalBinary(b []byte) error {
	var res ModelsRemoveInstancesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
