// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	stderrors "errors"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelsInstancePlanningDetail models instance planning detail
//
// swagger:model models.InstancePlanningDetail
type ModelsInstancePlanningDetail struct {

	// deployment details
	DeploymentDetails *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsDeploymentDetails `json:"deploymentDetails,omitempty"`

	// deployment extra
	DeploymentExtra any `json:"deploymentExtra,omitempty"`

	// instance summary
	InstanceSummary *HpcgitlabLabsLenovoComLocBackendCmdAPIModelsInstanceSummary `json:"instanceSummary,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// operation
	Operation string `json:"operation,omitempty"`
}

// Validate validates this models instance planning detail
func (m *ModelsInstancePlanningDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDeploymentDetails(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInstanceSummary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsInstancePlanningDetail) validateDeploymentDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.DeploymentDetails) { // not required
		return nil
	}

	if m.DeploymentDetails != nil {
		if err := m.DeploymentDetails.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deploymentDetails")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deploymentDetails")
			}

			return err
		}
	}

	return nil
}

func (m *ModelsInstancePlanningDetail) validateInstanceSummary(formats strfmt.Registry) error {
	if swag.IsZero(m.InstanceSummary) { // not required
		return nil
	}

	if m.InstanceSummary != nil {
		if err := m.InstanceSummary.Validate(formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instanceSummary")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instanceSummary")
			}

			return err
		}
	}

	return nil
}

// ContextValidate validate this models instance planning detail based on the context it is used
func (m *ModelsInstancePlanningDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateDeploymentDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateInstanceSummary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelsInstancePlanningDetail) contextValidateDeploymentDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.DeploymentDetails != nil {

		if swag.IsZero(m.DeploymentDetails) { // not required
			return nil
		}

		if err := m.DeploymentDetails.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("deploymentDetails")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("deploymentDetails")
			}

			return err
		}
	}

	return nil
}

func (m *ModelsInstancePlanningDetail) contextValidateInstanceSummary(ctx context.Context, formats strfmt.Registry) error {

	if m.InstanceSummary != nil {

		if swag.IsZero(m.InstanceSummary) { // not required
			return nil
		}

		if err := m.InstanceSummary.ContextValidate(ctx, formats); err != nil {
			ve := new(errors.Validation)
			if stderrors.As(err, &ve) {
				return ve.ValidateName("instanceSummary")
			}
			ce := new(errors.CompositeError)
			if stderrors.As(err, &ce) {
				return ce.ValidateName("instanceSummary")
			}

			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelsInstancePlanningDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelsInstancePlanningDetail) UnmarshalBinary(b []byte) error {
	var res ModelsInstancePlanningDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
