// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VaultschemaExternalVaultSP vaultschema external vault s p
//
// swagger:model vaultschema.ExternalVaultSP
type VaultschemaExternalVaultSP struct {

	// external read-write vault instance name
	Name string `json:"name,omitempty"`

	// secretpath inside the vault instance above
	SecretPath string `json:"secretPath,omitempty"`
}

// Validate validates this vaultschema external vault s p
func (m *VaultschemaExternalVaultSP) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this vaultschema external vault s p based on context it is used
func (m *VaultschemaExternalVaultSP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VaultschemaExternalVaultSP) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VaultschemaExternalVaultSP) UnmarshalBinary(b []byte) error {
	var res VaultschemaExternalVaultSP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
