// Code generated by go-swagger; DO NOT EDIT.

package task_management

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV1TaskManagementTasksUUIDParams creates a new DeleteAPIV1TaskManagementTasksUUIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIV1TaskManagementTasksUUIDParams() *DeleteAPIV1TaskManagementTasksUUIDParams {
	return &DeleteAPIV1TaskManagementTasksUUIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV1TaskManagementTasksUUIDParamsWithTimeout creates a new DeleteAPIV1TaskManagementTasksUUIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIV1TaskManagementTasksUUIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV1TaskManagementTasksUUIDParams {
	return &DeleteAPIV1TaskManagementTasksUUIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIV1TaskManagementTasksUUIDParamsWithContext creates a new DeleteAPIV1TaskManagementTasksUUIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIV1TaskManagementTasksUUIDParamsWithContext(ctx context.Context) *DeleteAPIV1TaskManagementTasksUUIDParams {
	return &DeleteAPIV1TaskManagementTasksUUIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIV1TaskManagementTasksUUIDParamsWithHTTPClient creates a new DeleteAPIV1TaskManagementTasksUUIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIV1TaskManagementTasksUUIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV1TaskManagementTasksUUIDParams {
	return &DeleteAPIV1TaskManagementTasksUUIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIV1TaskManagementTasksUUIDParams contains all the parameters to send to the API endpoint

	for the delete API v1 task management tasks UUID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIV1TaskManagementTasksUUIDParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	/* UUID.

	   task uuid
	*/
	UUID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API v1 task management tasks UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithDefaults() *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API v1 task management tasks UUID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithContext(ctx context.Context) *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithAuthorization(authorization string) *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithUUID adds the uuid to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WithUUID(uuid string) *DeleteAPIV1TaskManagementTasksUUIDParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the delete API v1 task management tasks UUID params
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) SetUUID(uuid string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV1TaskManagementTasksUUIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// path param uuid
	if err := r.SetPathParam("uuid", o.UUID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
