# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
    "**/*.md",
    "**/*.json",
    "**/VERSION",
    # decypt.py has a Lenovo license approved by OSPO
    "edge-node/filter_plugins/decrypt.py",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
