// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1CertUploadParams creates a new PostAPIV1CertUploadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1CertUploadParams() *PostAPIV1CertUploadParams {
	return &PostAPIV1CertUploadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1CertUploadParamsWithTimeout creates a new PostAPIV1CertUploadParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1CertUploadParamsWithTimeout(timeout time.Duration) *PostAPIV1CertUploadParams {
	return &PostAPIV1CertUploadParams{
		timeout: timeout,
	}
}

// NewPostAPIV1CertUploadParamsWithContext creates a new PostAPIV1CertUploadParams object
// with the ability to set a context for a request.
func NewPostAPIV1CertUploadParamsWithContext(ctx context.Context) *PostAPIV1CertUploadParams {
	return &PostAPIV1CertUploadParams{
		Context: ctx,
	}
}

// NewPostAPIV1CertUploadParamsWithHTTPClient creates a new PostAPIV1CertUploadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1CertUploadParamsWithHTTPClient(client *http.Client) *PostAPIV1CertUploadParams {
	return &PostAPIV1CertUploadParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1CertUploadParams contains all the parameters to send to the API endpoint

	for the post API v1 cert upload operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1CertUploadParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	/* File.

	   Filename
	*/
	File string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 cert upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1CertUploadParams) WithDefaults() *PostAPIV1CertUploadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 cert upload params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1CertUploadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) WithTimeout(timeout time.Duration) *PostAPIV1CertUploadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) WithContext(ctx context.Context) *PostAPIV1CertUploadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) WithHTTPClient(client *http.Client) *PostAPIV1CertUploadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) WithAuthorization(authorization string) *PostAPIV1CertUploadParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithFile adds the file to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) WithFile(file string) *PostAPIV1CertUploadParams {
	o.SetFile(file)
	return o
}

// SetFile adds the file to the post API v1 cert upload params
func (o *PostAPIV1CertUploadParams) SetFile(file string) {
	o.File = file
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1CertUploadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	// form param file
	frFile := o.File
	fFile := frFile
	if fFile != "" {
		if err := r.SetFormParam("file", fFile); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
