// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIV1CertResetParams creates a new PostAPIV1CertResetParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1CertResetParams() *PostAPIV1CertResetParams {
	return &PostAPIV1CertResetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1CertResetParamsWithTimeout creates a new PostAPIV1CertResetParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1CertResetParamsWithTimeout(timeout time.Duration) *PostAPIV1CertResetParams {
	return &PostAPIV1CertResetParams{
		timeout: timeout,
	}
}

// NewPostAPIV1CertResetParamsWithContext creates a new PostAPIV1CertResetParams object
// with the ability to set a context for a request.
func NewPostAPIV1CertResetParamsWithContext(ctx context.Context) *PostAPIV1CertResetParams {
	return &PostAPIV1CertResetParams{
		Context: ctx,
	}
}

// NewPostAPIV1CertResetParamsWithHTTPClient creates a new PostAPIV1CertResetParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1CertResetParamsWithHTTPClient(client *http.Client) *PostAPIV1CertResetParams {
	return &PostAPIV1CertResetParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1CertResetParams contains all the parameters to send to the API endpoint

	for the post API v1 cert reset operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1CertResetParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 cert reset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1CertResetParams) WithDefaults() *PostAPIV1CertResetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 cert reset params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1CertResetParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) WithTimeout(timeout time.Duration) *PostAPIV1CertResetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) WithContext(ctx context.Context) *PostAPIV1CertResetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) WithHTTPClient(client *http.Client) *PostAPIV1CertResetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) WithAuthorization(authorization string) *PostAPIV1CertResetParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 cert reset params
func (o *PostAPIV1CertResetParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1CertResetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
