// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	stderrors "errors"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// GetAPIV1DeploymentTemplatesReader is a Reader for the GetAPIV1DeploymentTemplates structure.
type GetAPIV1DeploymentTemplatesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV1DeploymentTemplatesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (any, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV1DeploymentTemplatesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetAPIV1DeploymentTemplatesBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetAPIV1DeploymentTemplatesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetAPIV1DeploymentTemplatesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/v1/deployment/templates] GetAPIV1DeploymentTemplates", response, response.Code())
	}
}

// NewGetAPIV1DeploymentTemplatesOK creates a GetAPIV1DeploymentTemplatesOK with default headers values
func NewGetAPIV1DeploymentTemplatesOK() *GetAPIV1DeploymentTemplatesOK {
	return &GetAPIV1DeploymentTemplatesOK{}
}

/*
GetAPIV1DeploymentTemplatesOK describes a response with status code 200, with default header values.

success
*/
type GetAPIV1DeploymentTemplatesOK struct {
	Payload *model.DtoTemplatesQryResponse
}

// IsSuccess returns true when this get Api v1 deployment templates o k response has a 2xx status code
func (o *GetAPIV1DeploymentTemplatesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v1 deployment templates o k response has a 3xx status code
func (o *GetAPIV1DeploymentTemplatesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 deployment templates o k response has a 4xx status code
func (o *GetAPIV1DeploymentTemplatesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 deployment templates o k response has a 5xx status code
func (o *GetAPIV1DeploymentTemplatesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 deployment templates o k response a status code equal to that given
func (o *GetAPIV1DeploymentTemplatesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v1 deployment templates o k response
func (o *GetAPIV1DeploymentTemplatesOK) Code() int {
	return 200
}

func (o *GetAPIV1DeploymentTemplatesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesOK %s", 200, payload)
}

func (o *GetAPIV1DeploymentTemplatesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesOK %s", 200, payload)
}

func (o *GetAPIV1DeploymentTemplatesOK) GetPayload() *model.DtoTemplatesQryResponse {
	return o.Payload
}

func (o *GetAPIV1DeploymentTemplatesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoTemplatesQryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1DeploymentTemplatesBadRequest creates a GetAPIV1DeploymentTemplatesBadRequest with default headers values
func NewGetAPIV1DeploymentTemplatesBadRequest() *GetAPIV1DeploymentTemplatesBadRequest {
	return &GetAPIV1DeploymentTemplatesBadRequest{}
}

/*
GetAPIV1DeploymentTemplatesBadRequest describes a response with status code 400, with default header values.

auth fail
*/
type GetAPIV1DeploymentTemplatesBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this get Api v1 deployment templates bad request response has a 2xx status code
func (o *GetAPIV1DeploymentTemplatesBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 deployment templates bad request response has a 3xx status code
func (o *GetAPIV1DeploymentTemplatesBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 deployment templates bad request response has a 4xx status code
func (o *GetAPIV1DeploymentTemplatesBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 deployment templates bad request response has a 5xx status code
func (o *GetAPIV1DeploymentTemplatesBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 deployment templates bad request response a status code equal to that given
func (o *GetAPIV1DeploymentTemplatesBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get Api v1 deployment templates bad request response
func (o *GetAPIV1DeploymentTemplatesBadRequest) Code() int {
	return 400
}

func (o *GetAPIV1DeploymentTemplatesBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesBadRequest %s", 400, payload)
}

func (o *GetAPIV1DeploymentTemplatesBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesBadRequest %s", 400, payload)
}

func (o *GetAPIV1DeploymentTemplatesBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *GetAPIV1DeploymentTemplatesBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1DeploymentTemplatesUnauthorized creates a GetAPIV1DeploymentTemplatesUnauthorized with default headers values
func NewGetAPIV1DeploymentTemplatesUnauthorized() *GetAPIV1DeploymentTemplatesUnauthorized {
	return &GetAPIV1DeploymentTemplatesUnauthorized{}
}

/*
GetAPIV1DeploymentTemplatesUnauthorized describes a response with status code 401, with default header values.

auth fail
*/
type GetAPIV1DeploymentTemplatesUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this get Api v1 deployment templates unauthorized response has a 2xx status code
func (o *GetAPIV1DeploymentTemplatesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 deployment templates unauthorized response has a 3xx status code
func (o *GetAPIV1DeploymentTemplatesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 deployment templates unauthorized response has a 4xx status code
func (o *GetAPIV1DeploymentTemplatesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get Api v1 deployment templates unauthorized response has a 5xx status code
func (o *GetAPIV1DeploymentTemplatesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v1 deployment templates unauthorized response a status code equal to that given
func (o *GetAPIV1DeploymentTemplatesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get Api v1 deployment templates unauthorized response
func (o *GetAPIV1DeploymentTemplatesUnauthorized) Code() int {
	return 401
}

func (o *GetAPIV1DeploymentTemplatesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesUnauthorized %s", 401, payload)
}

func (o *GetAPIV1DeploymentTemplatesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesUnauthorized %s", 401, payload)
}

func (o *GetAPIV1DeploymentTemplatesUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *GetAPIV1DeploymentTemplatesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}

// NewGetAPIV1DeploymentTemplatesInternalServerError creates a GetAPIV1DeploymentTemplatesInternalServerError with default headers values
func NewGetAPIV1DeploymentTemplatesInternalServerError() *GetAPIV1DeploymentTemplatesInternalServerError {
	return &GetAPIV1DeploymentTemplatesInternalServerError{}
}

/*
GetAPIV1DeploymentTemplatesInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type GetAPIV1DeploymentTemplatesInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this get Api v1 deployment templates internal server error response has a 2xx status code
func (o *GetAPIV1DeploymentTemplatesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get Api v1 deployment templates internal server error response has a 3xx status code
func (o *GetAPIV1DeploymentTemplatesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v1 deployment templates internal server error response has a 4xx status code
func (o *GetAPIV1DeploymentTemplatesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v1 deployment templates internal server error response has a 5xx status code
func (o *GetAPIV1DeploymentTemplatesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get Api v1 deployment templates internal server error response a status code equal to that given
func (o *GetAPIV1DeploymentTemplatesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get Api v1 deployment templates internal server error response
func (o *GetAPIV1DeploymentTemplatesInternalServerError) Code() int {
	return 500
}

func (o *GetAPIV1DeploymentTemplatesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DeploymentTemplatesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v1/deployment/templates][%d] getApiV1DeploymentTemplatesInternalServerError %s", 500, payload)
}

func (o *GetAPIV1DeploymentTemplatesInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *GetAPIV1DeploymentTemplatesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && !stderrors.Is(err, io.EOF) {
		return err
	}

	return nil
}
