// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// PostAPIV1DeploymentTemplatesUpdateReader is a Reader for the PostAPIV1DeploymentTemplatesUpdate structure.
type PostAPIV1DeploymentTemplatesUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1DeploymentTemplatesUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV1DeploymentTemplatesUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1DeploymentTemplatesUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1DeploymentTemplatesUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1DeploymentTemplatesUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/deployment/templates/update] PostAPIV1DeploymentTemplatesUpdate", response, response.Code())
	}
}

// NewPostAPIV1DeploymentTemplatesUpdateOK creates a PostAPIV1DeploymentTemplatesUpdateOK with default headers values
func NewPostAPIV1DeploymentTemplatesUpdateOK() *PostAPIV1DeploymentTemplatesUpdateOK {
	return &PostAPIV1DeploymentTemplatesUpdateOK{}
}

/*
PostAPIV1DeploymentTemplatesUpdateOK describes a response with status code 200, with default header values.

success
*/
type PostAPIV1DeploymentTemplatesUpdateOK struct {
	Payload *model.DtoTemplateQryResponse
}

// IsSuccess returns true when this post Api v1 deployment templates update o k response has a 2xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 deployment templates update o k response has a 3xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment templates update o k response has a 4xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployment templates update o k response has a 5xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment templates update o k response a status code equal to that given
func (o *PostAPIV1DeploymentTemplatesUpdateOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v1 deployment templates update o k response
func (o *PostAPIV1DeploymentTemplatesUpdateOK) Code() int {
	return 200
}

func (o *PostAPIV1DeploymentTemplatesUpdateOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateOK %s", 200, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateOK %s", 200, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateOK) GetPayload() *model.DtoTemplateQryResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentTemplatesUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoTemplateQryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentTemplatesUpdateBadRequest creates a PostAPIV1DeploymentTemplatesUpdateBadRequest with default headers values
func NewPostAPIV1DeploymentTemplatesUpdateBadRequest() *PostAPIV1DeploymentTemplatesUpdateBadRequest {
	return &PostAPIV1DeploymentTemplatesUpdateBadRequest{}
}

/*
PostAPIV1DeploymentTemplatesUpdateBadRequest describes a response with status code 400, with default header values.

auth fail
*/
type PostAPIV1DeploymentTemplatesUpdateBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment templates update bad request response has a 2xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment templates update bad request response has a 3xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment templates update bad request response has a 4xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployment templates update bad request response has a 5xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment templates update bad request response a status code equal to that given
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 deployment templates update bad request response
func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentTemplatesUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentTemplatesUpdateUnauthorized creates a PostAPIV1DeploymentTemplatesUpdateUnauthorized with default headers values
func NewPostAPIV1DeploymentTemplatesUpdateUnauthorized() *PostAPIV1DeploymentTemplatesUpdateUnauthorized {
	return &PostAPIV1DeploymentTemplatesUpdateUnauthorized{}
}

/*
PostAPIV1DeploymentTemplatesUpdateUnauthorized describes a response with status code 401, with default header values.

auth fail
*/
type PostAPIV1DeploymentTemplatesUpdateUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment templates update unauthorized response has a 2xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment templates update unauthorized response has a 3xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment templates update unauthorized response has a 4xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployment templates update unauthorized response has a 5xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment templates update unauthorized response a status code equal to that given
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 deployment templates update unauthorized response
func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentTemplatesUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentTemplatesUpdateInternalServerError creates a PostAPIV1DeploymentTemplatesUpdateInternalServerError with default headers values
func NewPostAPIV1DeploymentTemplatesUpdateInternalServerError() *PostAPIV1DeploymentTemplatesUpdateInternalServerError {
	return &PostAPIV1DeploymentTemplatesUpdateInternalServerError{}
}

/*
PostAPIV1DeploymentTemplatesUpdateInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type PostAPIV1DeploymentTemplatesUpdateInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment templates update internal server error response has a 2xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment templates update internal server error response has a 3xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment templates update internal server error response has a 4xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployment templates update internal server error response has a 5xx status code
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 deployment templates update internal server error response a status code equal to that given
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 deployment templates update internal server error response
func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/templates/update][%d] postApiV1DeploymentTemplatesUpdateInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentTemplatesUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
