// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// NewPostAPIV1DeploymentInstancesCreateParams creates a new PostAPIV1DeploymentInstancesCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1DeploymentInstancesCreateParams() *PostAPIV1DeploymentInstancesCreateParams {
	return &PostAPIV1DeploymentInstancesCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1DeploymentInstancesCreateParamsWithTimeout creates a new PostAPIV1DeploymentInstancesCreateParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1DeploymentInstancesCreateParamsWithTimeout(timeout time.Duration) *PostAPIV1DeploymentInstancesCreateParams {
	return &PostAPIV1DeploymentInstancesCreateParams{
		timeout: timeout,
	}
}

// NewPostAPIV1DeploymentInstancesCreateParamsWithContext creates a new PostAPIV1DeploymentInstancesCreateParams object
// with the ability to set a context for a request.
func NewPostAPIV1DeploymentInstancesCreateParamsWithContext(ctx context.Context) *PostAPIV1DeploymentInstancesCreateParams {
	return &PostAPIV1DeploymentInstancesCreateParams{
		Context: ctx,
	}
}

// NewPostAPIV1DeploymentInstancesCreateParamsWithHTTPClient creates a new PostAPIV1DeploymentInstancesCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1DeploymentInstancesCreateParamsWithHTTPClient(client *http.Client) *PostAPIV1DeploymentInstancesCreateParams {
	return &PostAPIV1DeploymentInstancesCreateParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1DeploymentInstancesCreateParams contains all the parameters to send to the API endpoint

	for the post API v1 deployment instances create operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1DeploymentInstancesCreateParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	/* Body.

	   Request body for creating instances
	*/
	Body *model.DtoCreateInstanceRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 deployment instances create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1DeploymentInstancesCreateParams) WithDefaults() *PostAPIV1DeploymentInstancesCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 deployment instances create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1DeploymentInstancesCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) WithTimeout(timeout time.Duration) *PostAPIV1DeploymentInstancesCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) WithContext(ctx context.Context) *PostAPIV1DeploymentInstancesCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) WithHTTPClient(client *http.Client) *PostAPIV1DeploymentInstancesCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) WithAuthorization(authorization string) *PostAPIV1DeploymentInstancesCreateParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) WithBody(body *model.DtoCreateInstanceRequest) *PostAPIV1DeploymentInstancesCreateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v1 deployment instances create params
func (o *PostAPIV1DeploymentInstancesCreateParams) SetBody(body *model.DtoCreateInstanceRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1DeploymentInstancesCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
