// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// NewPostAPIV1DeploymentTemplatesParams creates a new PostAPIV1DeploymentTemplatesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1DeploymentTemplatesParams() *PostAPIV1DeploymentTemplatesParams {
	return &PostAPIV1DeploymentTemplatesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1DeploymentTemplatesParamsWithTimeout creates a new PostAPIV1DeploymentTemplatesParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1DeploymentTemplatesParamsWithTimeout(timeout time.Duration) *PostAPIV1DeploymentTemplatesParams {
	return &PostAPIV1DeploymentTemplatesParams{
		timeout: timeout,
	}
}

// NewPostAPIV1DeploymentTemplatesParamsWithContext creates a new PostAPIV1DeploymentTemplatesParams object
// with the ability to set a context for a request.
func NewPostAPIV1DeploymentTemplatesParamsWithContext(ctx context.Context) *PostAPIV1DeploymentTemplatesParams {
	return &PostAPIV1DeploymentTemplatesParams{
		Context: ctx,
	}
}

// NewPostAPIV1DeploymentTemplatesParamsWithHTTPClient creates a new PostAPIV1DeploymentTemplatesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1DeploymentTemplatesParamsWithHTTPClient(client *http.Client) *PostAPIV1DeploymentTemplatesParams {
	return &PostAPIV1DeploymentTemplatesParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1DeploymentTemplatesParams contains all the parameters to send to the API endpoint

	for the post API v1 deployment templates operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1DeploymentTemplatesParams struct {

	/* Authorization.

	   Bearer $token
	*/
	Authorization string

	/* Body.

	   request cloud-services params
	*/
	Body *model.DtoCreateTemplateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 deployment templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1DeploymentTemplatesParams) WithDefaults() *PostAPIV1DeploymentTemplatesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 deployment templates params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1DeploymentTemplatesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) WithTimeout(timeout time.Duration) *PostAPIV1DeploymentTemplatesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) WithContext(ctx context.Context) *PostAPIV1DeploymentTemplatesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) WithHTTPClient(client *http.Client) *PostAPIV1DeploymentTemplatesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthorization adds the authorization to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) WithAuthorization(authorization string) *PostAPIV1DeploymentTemplatesParams {
	o.SetAuthorization(authorization)
	return o
}

// SetAuthorization adds the authorization to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) SetAuthorization(authorization string) {
	o.Authorization = authorization
}

// WithBody adds the body to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) WithBody(body *model.DtoCreateTemplateRequest) *PostAPIV1DeploymentTemplatesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v1 deployment templates params
func (o *PostAPIV1DeploymentTemplatesParams) SetBody(body *model.DtoCreateTemplateRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1DeploymentTemplatesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param Authorization
	if err := r.SetHeaderParam("Authorization", o.Authorization); err != nil {
		return err
	}
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
