// Code generated by go-swagger; DO NOT EDIT.

package deployment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/open-edge-platform/infra-external/loca-onboarding/v2/pkg/api/loca/v3.3/model"
)

// PostAPIV1DeploymentInstancesRemoveReader is a Reader for the PostAPIV1DeploymentInstancesRemove structure.
type PostAPIV1DeploymentInstancesRemoveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV1DeploymentInstancesRemoveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostAPIV1DeploymentInstancesRemoveCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPostAPIV1DeploymentInstancesRemoveBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPostAPIV1DeploymentInstancesRemoveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewPostAPIV1DeploymentInstancesRemoveInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /api/v1/deployment/instances/remove] PostAPIV1DeploymentInstancesRemove", response, response.Code())
	}
}

// NewPostAPIV1DeploymentInstancesRemoveCreated creates a PostAPIV1DeploymentInstancesRemoveCreated with default headers values
func NewPostAPIV1DeploymentInstancesRemoveCreated() *PostAPIV1DeploymentInstancesRemoveCreated {
	return &PostAPIV1DeploymentInstancesRemoveCreated{}
}

/*
PostAPIV1DeploymentInstancesRemoveCreated describes a response with status code 201, with default header values.

success
*/
type PostAPIV1DeploymentInstancesRemoveCreated struct {
	Payload *model.DtoCreatedWorkflowResponse
}

// IsSuccess returns true when this post Api v1 deployment instances remove created response has a 2xx status code
func (o *PostAPIV1DeploymentInstancesRemoveCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v1 deployment instances remove created response has a 3xx status code
func (o *PostAPIV1DeploymentInstancesRemoveCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment instances remove created response has a 4xx status code
func (o *PostAPIV1DeploymentInstancesRemoveCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployment instances remove created response has a 5xx status code
func (o *PostAPIV1DeploymentInstancesRemoveCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment instances remove created response a status code equal to that given
func (o *PostAPIV1DeploymentInstancesRemoveCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the post Api v1 deployment instances remove created response
func (o *PostAPIV1DeploymentInstancesRemoveCreated) Code() int {
	return 201
}

func (o *PostAPIV1DeploymentInstancesRemoveCreated) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveCreated %s", 201, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveCreated) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveCreated %s", 201, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveCreated) GetPayload() *model.DtoCreatedWorkflowResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentInstancesRemoveCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoCreatedWorkflowResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentInstancesRemoveBadRequest creates a PostAPIV1DeploymentInstancesRemoveBadRequest with default headers values
func NewPostAPIV1DeploymentInstancesRemoveBadRequest() *PostAPIV1DeploymentInstancesRemoveBadRequest {
	return &PostAPIV1DeploymentInstancesRemoveBadRequest{}
}

/*
PostAPIV1DeploymentInstancesRemoveBadRequest describes a response with status code 400, with default header values.

auth fail
*/
type PostAPIV1DeploymentInstancesRemoveBadRequest struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment instances remove bad request response has a 2xx status code
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment instances remove bad request response has a 3xx status code
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment instances remove bad request response has a 4xx status code
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployment instances remove bad request response has a 5xx status code
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment instances remove bad request response a status code equal to that given
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the post Api v1 deployment instances remove bad request response
func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) Code() int {
	return 400
}

func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveBadRequest %s", 400, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentInstancesRemoveBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentInstancesRemoveUnauthorized creates a PostAPIV1DeploymentInstancesRemoveUnauthorized with default headers values
func NewPostAPIV1DeploymentInstancesRemoveUnauthorized() *PostAPIV1DeploymentInstancesRemoveUnauthorized {
	return &PostAPIV1DeploymentInstancesRemoveUnauthorized{}
}

/*
PostAPIV1DeploymentInstancesRemoveUnauthorized describes a response with status code 401, with default header values.

auth fail
*/
type PostAPIV1DeploymentInstancesRemoveUnauthorized struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment instances remove unauthorized response has a 2xx status code
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment instances remove unauthorized response has a 3xx status code
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment instances remove unauthorized response has a 4xx status code
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this post Api v1 deployment instances remove unauthorized response has a 5xx status code
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v1 deployment instances remove unauthorized response a status code equal to that given
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the post Api v1 deployment instances remove unauthorized response
func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) Code() int {
	return 401
}

func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveUnauthorized %s", 401, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentInstancesRemoveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAPIV1DeploymentInstancesRemoveInternalServerError creates a PostAPIV1DeploymentInstancesRemoveInternalServerError with default headers values
func NewPostAPIV1DeploymentInstancesRemoveInternalServerError() *PostAPIV1DeploymentInstancesRemoveInternalServerError {
	return &PostAPIV1DeploymentInstancesRemoveInternalServerError{}
}

/*
PostAPIV1DeploymentInstancesRemoveInternalServerError describes a response with status code 500, with default header values.

internal error
*/
type PostAPIV1DeploymentInstancesRemoveInternalServerError struct {
	Payload *model.DtoErrResponse
}

// IsSuccess returns true when this post Api v1 deployment instances remove internal server error response has a 2xx status code
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this post Api v1 deployment instances remove internal server error response has a 3xx status code
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v1 deployment instances remove internal server error response has a 4xx status code
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v1 deployment instances remove internal server error response has a 5xx status code
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this post Api v1 deployment instances remove internal server error response a status code equal to that given
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the post Api v1 deployment instances remove internal server error response
func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) Code() int {
	return 500
}

func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v1/deployment/instances/remove][%d] postApiV1DeploymentInstancesRemoveInternalServerError %s", 500, payload)
}

func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) GetPayload() *model.DtoErrResponse {
	return o.Payload
}

func (o *PostAPIV1DeploymentInstancesRemoveInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.DtoErrResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
